/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author marcos
 */
public class ConfiguracaoPersistenciaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfiguracaoPersistenciaView
     */
    public ConfiguracaoPersistenciaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonMYSQL = new javax.swing.JRadioButton();
        jRadioButtonSQLITE = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonTXT = new javax.swing.JRadioButton();
        jRadioButtonJSON = new javax.swing.JRadioButton();
        jRadioButtonXML = new javax.swing.JRadioButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 320));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Configuração");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Persistência do Funcionário:");

        jRadioButtonMYSQL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButtonMYSQL.setText("MYSQL");

        jRadioButtonSQLITE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButtonSQLITE.setText("SQLITE");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Persistência do Log:");

        jRadioButtonTXT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButtonTXT.setText("TXT");

        jRadioButtonJSON.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButtonJSON.setText("JSON");

        jRadioButtonXML.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRadioButtonXML.setText("XML");

        jButtonSalvar.setText("Salvar");

        jButtonFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMYSQL)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonSQLITE))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonTXT)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonJSON)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonXML)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(jButtonFechar)
                                .addGap(68, 68, 68)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonFechar, jButtonSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMYSQL)
                    .addComponent(jRadioButtonSQLITE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTXT)
                    .addComponent(jRadioButtonJSON)
                    .addComponent(jRadioButtonXML))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonSalvar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonFechar, jButtonSalvar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonFechar() {
        return jButtonFechar;
    }

    public JButton getjButtonSalvar() {
        return jButtonSalvar;
    }

    public JRadioButton getjRadioButtonJSON() {
        return jRadioButtonJSON;
    }

    public JRadioButton getjRadioButtonMYSQL() {
        return jRadioButtonMYSQL;
    }

    public JRadioButton getjRadioButtonSQLITE() {
        return jRadioButtonSQLITE;
    }

    public JRadioButton getjRadioButtonTXT() {
        return jRadioButtonTXT;
    }

    public JRadioButton getjRadioButtonXML() {
        return jRadioButtonXML;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonJSON;
    private javax.swing.JRadioButton jRadioButtonMYSQL;
    private javax.swing.JRadioButton jRadioButtonSQLITE;
    private javax.swing.JRadioButton jRadioButtonTXT;
    private javax.swing.JRadioButton jRadioButtonXML;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
